### ISSUE TITLE
Timeout::Error: execution expired during appliance kickstart

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/manageiq-appliance-build#5]
During rake assets:clean:

```
DEPRECATION WARNING: You did not specify a `log_level` in `production.rb`. Currently, the default value for `log_level` is `:info` for the production environment and `:debug` in all other environments. In Rails 5 the default value will be unified to `:debug` across all environments. To preserve the current setting, add the following line to your `production.rb`:

   config.log_level = :info

. (called from block in tsort_each at /opt/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226)
{:lineno=>[1, "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_lexer.rb:855", nil]}
{:lineno=>[1, "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_lexer.rb:855", nil]}
{:scan=>["class", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>[" ", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>["UiTaskSet", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>[" ", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>["<", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>[" ", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
...
...
Thousands of these ruby_parser lines...
...
...
{:scan=>[" ", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>["\"expression\"", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:lineno=>[455, "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:837", ", \"expression\")\n      next(h) unless exp"]}
{:scan=>[",", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>[" ", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>["\"expression\"", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:lineno=>[455, "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:837", ")\n      next(h) unless exp\n      next(h)"]}
{:scan=>[")", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>["\n", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:lineno=>[456, "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_lexer.rb:455", "      next(h) unless exp\n      next(h) u"]}
{:scan=>[" ", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>[" ", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>[" ", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>[" ", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>[" ", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>[" ", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>["next", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>["(", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>["h", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>[")", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>[" ", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>["unless", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>[" ", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>["exp", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:scan=>["\n", "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_parser_extras.rb:919"]}
{:lineno=>[457, "/opt/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/ruby_parser-3.7.0/lib/ruby_lexer.rb:455", "      next(h) unless exp.detect {|e| e[\""]}
rake aborted!
Timeout::Error: execution expired
/var/www/miq/vmdb/lib/extensions/as_const_missing_with_sti.rb:36:in `classes_in'
/var/www/miq/vmdb/lib/extensions/as_const_missing_with_sti.rb:126:in `block in class_inheritance_relationships'
/var/www/miq/vmdb/lib/extensions/as_const_missing_with_sti.rb:125:in `glob'
/var/www/miq/vmdb/lib/extensions/as_const_missing_with_sti.rb:125:in `class_inheritance_relationships'
/var/www/miq/vmdb/lib/extensions/as_const_missing_with_sti.rb:168:in `enqueue_subclasses'
/var/www/miq/vmdb/lib/extensions/as_const_missing_with_sti.rb:81:in `block (2 levels) in const_missing_with_sti'
/var/www/miq/vmdb/lib/extensions/as_const_missing_with_sti.rb:80:in `tap'
/var/www/miq/vmdb/lib/extensions/as_const_missing_with_sti.rb:80:in `block in const_missing_with_sti'
/var/www/miq/vmdb/lib/extensions/as_const_missing_with_sti.rb:176:in `nest'
/var/www/miq/vmdb/lib/extensions/as_const_missing_with_sti.rb:79:in `const_missing_with_sti'
/var/www/miq/vmdb/config/initializers/fast_gettext.rb:7:in `<top (required)>'
/var/www/miq/vmdb/config/environment.rb:5:in `<top (required)>'
/var/www/miq/vmdb/lib/tasks/evm.rake:41:in `block (2 levels) in <top (required)>'
Tasks: TOP => environment
(See full trace by running task with --trace)
```

**Comment by jrafanie** [comment]
evm.rake:41 is here:  https://github.com/ManageIQ/manageiq/blob/3e90bae68067d26a45c2076d698ce945d8a204b0/lib/tasks/evm.rake#L41

Which runs:
`Rake::Task["assets:clean"].invoke`

Note, ruby_parser was upgraded [here via the brakeman upgrade](https://github.com/ManageIQ/manageiq/commit/a78d508ce6903c4cdaf1497d93cbdfb73113d93d)

@matthewd found that ruby_parser had the debug logging [here](https://github.com/seattlerb/ruby_parser/commit/4b301272c4627a2f7d7d3900c879b8d4e05094bb)

**Comment by jrafanie** [comment]
It turns out that within the kickstart %post section, DEBUG is set but empty so unsetting it at the very beginning should fix this issue for us.
