### ISSUE TITLE
release-build.sh master -> Command exited with non-zero status 1

### ISSUE THREAD

**Issue by maly-glod** [ManageIQ/manageiq-appliance-build#526]
Hi, guys 

I'm trying to build miq appliance. I was managed to install environment with the "iPXE boot script for the kickstart", but during applience building I`m getting this error:
```
warning: Duplicate build-ids /root/rpmbuild/BUILDROOT/manageiq-16.0.0-0.el8.x86_64/opt/manageiq/manageiq-gemset/extensions/x86_64-linux/3.0.0/qpid_proton-0.30.0/cproton.so and /root/rpmbuild/BUILDROOT/manageiq-16.0.0-0.el8.x86_64/opt/manageiq/manageiq-gemset/gems/qpid_proton-0.30.0/ext/cproton/cproton.so
Provides: libhttp-parser-ext.so()(64bit) librdkafka.so.1()(64bit) libsass.so()(64bit) manageiq-gemset = 16.0.0-0.el8 manageiq-gemset(x86-64) = 16.0.0-0.el8
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires: /bin/bash /bin/sh /usr/bin/bash /usr/bin/env /usr/bin/gem /usr/bin/rake /usr/bin/ruby /usr/bin/sh /usr/libexec/platform-python ld-linux-x86-64.so.2()(64bit) ld-linux-x86-64.so.2(GLIBC_2.3)(64bit) libc.so.6()(64bit) libc.so.6(GLIBC_2.14)(64bit) libc.so.6(GLIBC_2.16)(64bit) libc.so.6(GLIBC_2.17)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libc.so.6(GLIBC_2.25)(64bit) libc.so.6(GLIBC_2.28)(64bit) libc.so.6(GLIBC_2.3)(64bit) libc.so.6(GLIBC_2.3.2)(64bit) libc.so.6(GLIBC_2.3.4)(64bit) libc.so.6(GLIBC_2.4)(64bit) libc.so.6(GLIBC_2.7)(64bit) libc.so.6(GLIBC_2.8)(64bit) libc.so.6(GLIBC_2.9)(64bit) libcrypto.so.1.1()(64bit) libcrypto.so.1.1(OPENSSL_1_1_0)(64bit) libcurl.so.4()(64bit) libdl.so.2()(64bit) libdl.so.2(GLIBC_2.2.5)(64bit) libgcc_s.so.1()(64bit) libgcc_s.so.1(GCC_3.0)(64bit) liblzma.so.5()(64bit) libm.so.6()(64bit) libm.so.6(GLIBC_2.2.5)(64bit) libpq.so.5()(64bit) libpq.so.5(RHPG_10)(64bit) libpq.so.5(RHPG_12)(64bit) libpq.so.5(RHPG_9.6)(64bit) libpthread.so.0()(64bit) libpthread.so.0(GLIBC_2.12)(64bit) libpthread.so.0(GLIBC_2.2.5)(64bit) libpthread.so.0(GLIBC_2.28)(64bit) libpthread.so.0(GLIBC_2.3.2)(64bit) libqpid-proton.so.11()(64bit) librt.so.1()(64bit) libruby.so.3.0()(64bit) libssh2.so.1()(64bit) libssl.so.1.1()(64bit) libssl.so.1.1(OPENSSL_1_1_0)(64bit) libstdc++.so.6()(64bit) libstdc++.so.6(CXXABI_1.3)(64bit) libstdc++.so.6(CXXABI_1.3.5)(64bit) libstdc++.so.6(CXXABI_1.3.8)(64bit) libstdc++.so.6(GLIBCXX_3.4)(64bit) libstdc++.so.6(GLIBCXX_3.4.11)(64bit) libstdc++.so.6(GLIBCXX_3.4.18)(64bit) libstdc++.so.6(GLIBCXX_3.4.20)(64bit) libstdc++.so.6(GLIBCXX_3.4.21)(64bit) libstdc++.so.6(GLIBCXX_3.4.9)(64bit) libxml2.so.2()(64bit) libxml2.so.2(LIBXML2_2.4.30)(64bit) libxml2.so.2(LIBXML2_2.5.0)(64bit) libxml2.so.2(LIBXML2_2.5.7)(64bit) libxml2.so.2(LIBXML2_2.6.0)(64bit) libxml2.so.2(LIBXML2_2.6.5)(64bit) libz.so.1()(64bit) libz.so.1(ZLIB_1.2.0)(64bit) libzstd.so.1()(64bit) rtld(GNU_HASH)
Processing files: manageiq-gemset-services-16.0.0-0.el8.x86_64
Provides: manageiq-gemset-services = 16.0.0-0.el8 manageiq-gemset-services(x86-64) = 16.0.0-0.el8
Requires(interp): /bin/sh
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires(post): /bin/sh
Processing files: manageiq-pods-16.0.0-0.el8.x86_64
Processing files: manageiq-system-16.0.0-0.el8.x86_64
Provides: manageiq-system = 16.0.0-0.el8 manageiq-system(x86-64) = 16.0.0-0.el8
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires: /bin/bash /bin/sh /usr/bin/ruby
Processing files: manageiq-ui-16.0.0-0.el8.x86_64
Provides: config(manageiq-ui) = 16.0.0-0.el8 manageiq-ui = 16.0.0-0.el8 manageiq-ui(x86-64) = 16.0.0-0.el8
Requires(interp): /bin/sh
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires(post): /bin/sh
Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/rpmbuild/BUILDROOT/manageiq-16.0.0-0.el8.x86_64
Wrote: /root/BUILD/rpms/x86_64/manageiq-16.0.0-0.el8.src.rpm
Wrote: /root/BUILD/rpms/x86_64/manageiq-appliance-16.0.0-0.el8.x86_64.rpm
Wrote: /root/BUILD/rpms/x86_64/manageiq-appliance-tools-16.0.0-0.el8.x86_64.rpm
Wrote: /root/BUILD/rpms/x86_64/manageiq-core-16.0.0-0.el8.x86_64.rpm
Wrote: /root/BUILD/rpms/x86_64/manageiq-core-services-16.0.0-0.el8.x86_64.rpm
Wrote: /root/BUILD/rpms/x86_64/manageiq-gemset-16.0.0-0.el8.x86_64.rpm
Wrote: /root/BUILD/rpms/x86_64/manageiq-gemset-services-16.0.0-0.el8.x86_64.rpm
Wrote: /root/BUILD/rpms/x86_64/manageiq-pods-16.0.0-0.el8.x86_64.rpm
Wrote: /root/BUILD/rpms/x86_64/manageiq-system-16.0.0-0.el8.x86_64.rpm
Wrote: /root/BUILD/rpms/x86_64/manageiq-ui-16.0.0-0.el8.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.xinrIN
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd manageiq-manifest-16.0.0
+ rm -rf /root/rpmbuild/BUILDROOT/manageiq-16.0.0-0.el8.x86_64
+ exit 0
/root/.gem/ruby/gems/aws-sigv4-1.5.1/lib/aws-sigv4/signer.rb:654:in `extract_credentials_provider': missing credentials, provide credentials with one of the following options: (Aws::Sigv4::Errors::MissingCredentialsError)
  - :access_key_id and :secret_access_key
  - :credentials
  - :credentials_provider
	from /root/.gem/ruby/gems/aws-sigv4-1.5.1/lib/aws-sigv4/signer.rb:144:in `initialize'
	from /root/.gem/ruby/gems/aws-sdk-s3-1.114.0/lib/aws-sdk-s3/plugins/s3_signer.rb:235:in `new'
	from /root/.gem/ruby/gems/aws-sdk-s3-1.114.0/lib/aws-sdk-s3/plugins/s3_signer.rb:235:in `build_v4_signer'
	from /root/.gem/ruby/gems/aws-sdk-s3-1.114.0/lib/aws-sdk-s3/plugins/s3_signer.rb:14:in `block in <class:S3Signer>'
	from /root/.gem/ruby/gems/aws-sdk-core-3.150.0/lib/seahorse/client/configuration.rb:72:in `call'
	from /root/.gem/ruby/gems/aws-sdk-core-3.150.0/lib/seahorse/client/configuration.rb:219:in `block in resolve_defaults'
	from /root/.gem/ruby/gems/aws-sdk-core-3.150.0/lib/seahorse/client/configuration.rb:59:in `each'
	from /root/.gem/ruby/gems/aws-sdk-core-3.150.0/lib/seahorse/client/configuration.rb:59:in `each'
	from /root/.gem/ruby/gems/aws-sdk-core-3.150.0/lib/seahorse/client/configuration.rb:218:in `resolve_defaults'
	from /root/.gem/ruby/gems/aws-sdk-core-3.150.0/lib/seahorse/client/configuration.rb:211:in `value_at'
	from /root/.gem/ruby/gems/aws-sdk-core-3.150.0/lib/seahorse/client/configuration.rb:191:in `block in resolve'
	from /usr/share/ruby/set.rb:328:in `each_key'
	from /usr/share/ruby/set.rb:328:in `each'
	from /root/.gem/ruby/gems/aws-sdk-core-3.150.0/lib/seahorse/client/configuration.rb:191:in `resolve'
	from /root/.gem/ruby/gems/aws-sdk-core-3.150.0/lib/seahorse/client/configuration.rb:179:in `apply_defaults'
	from /root/.gem/ruby/gems/aws-sdk-core-3.150.0/lib/seahorse/client/configuration.rb:152:in `build!'
	from /root/.gem/ruby/gems/aws-sdk-core-3.150.0/lib/seahorse/client/base.rb:65:in `build_config'
	from /root/.gem/ruby/gems/aws-sdk-core-3.150.0/lib/seahorse/client/base.rb:22:in `initialize'
	from /root/.gem/ruby/gems/aws-sdk-s3-1.114.0/lib/aws-sdk-s3/client.rb:435:in `initialize'
	from /root/.gem/ruby/gems/aws-sdk-core-3.150.0/lib/seahorse/client/base.rb:102:in `new'
	from /build_scripts/lib/manageiq/rpm_build/s3_common.rb:9:in `client'
	from /build_scripts/lib/manageiq/rpm_build/rpm_repo.rb:27:in `block (3 levels) in update'
	from /root/.gem/ruby/gems/config-4.0.0/lib/config/options.rb:87:in `each'
	from /root/.gem/ruby/gems/config-4.0.0/lib/config/options.rb:87:in `each'
	from /build_scripts/lib/manageiq/rpm_build/rpm_repo.rb:26:in `block (2 levels) in update'
	from /root/.gem/ruby/gems/config-4.0.0/lib/config/options.rb:87:in `each'
	from /root/.gem/ruby/gems/config-4.0.0/lib/config/options.rb:87:in `each'
	from /build_scripts/lib/manageiq/rpm_build/rpm_repo.rb:25:in `block in update'
	from /usr/share/ruby/tmpdir.rb:89:in `mktmpdir'
	from /build_scripts/lib/manageiq/rpm_build/rpm_repo.rb:11:in `update'
	from bin/build.rb:52:in `<main>'
Downloading required RPMs...
Command exited with non-zero status 1
```

Am I doing something wrong? I am trying to build miq applience (from master branch) for openstack environment.

Full log:
[master_rpm.log](https://github.com/ManageIQ/manageiq-appliance-build/files/9628180/master_rpm.log)

**Comment by bdunne** [comment]
https://github.com/ManageIQ/manageiq-appliance-build/blob/39ce38a82a107bd128e3c6226423d04231629796/bin/rpm-build.sh#L35 tells the RPM build to `--update-rpm-repo` which requires credentials.  A couple lines down from there you can see that it maps the OPTIONS fie into the RPM build container, you'll need to set credentials there.

**Comment by Fryguy** [comment]
Closing as the question was answered
